/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSistemSekolahRouteImport } from './routes/_authenticated/sistem/sekolah'
import { Route as AuthenticatedSistemPenggunaRouteImport } from './routes/_authenticated/sistem/pengguna'
import { Route as AuthenticatedSistemPengaturanRouteImport } from './routes/_authenticated/sistem/pengaturan'
import { Route as AuthenticatedSistemAuditRouteImport } from './routes/_authenticated/sistem/audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSistemSekolahRoute =
  AuthenticatedSistemSekolahRouteImport.update({
    id: '/sistem/sekolah',
    path: '/sistem/sekolah',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemPenggunaRoute =
  AuthenticatedSistemPenggunaRouteImport.update({
    id: '/sistem/pengguna',
    path: '/sistem/pengguna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemPengaturanRoute =
  AuthenticatedSistemPengaturanRouteImport.update({
    id: '/sistem/pengaturan',
    path: '/sistem/pengaturan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSistemAuditRoute =
  AuthenticatedSistemAuditRouteImport.update({
    id: '/sistem/audit',
    path: '/sistem/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/sistem/audit': typeof AuthenticatedSistemAuditRoute
  '/_authenticated/sistem/pengaturan': typeof AuthenticatedSistemPengaturanRoute
  '/_authenticated/sistem/pengguna': typeof AuthenticatedSistemPenggunaRoute
  '/_authenticated/sistem/sekolah': typeof AuthenticatedSistemSekolahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sistem/audit'
    | '/sistem/pengaturan'
    | '/sistem/pengguna'
    | '/sistem/sekolah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sistem/audit'
    | '/sistem/pengaturan'
    | '/sistem/pengguna'
    | '/sistem/sekolah'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/sistem/audit'
    | '/_authenticated/sistem/pengaturan'
    | '/_authenticated/sistem/pengguna'
    | '/_authenticated/sistem/sekolah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/sekolah': {
      id: '/_authenticated/sistem/sekolah'
      path: '/sistem/sekolah'
      fullPath: '/sistem/sekolah'
      preLoaderRoute: typeof AuthenticatedSistemSekolahRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/pengguna': {
      id: '/_authenticated/sistem/pengguna'
      path: '/sistem/pengguna'
      fullPath: '/sistem/pengguna'
      preLoaderRoute: typeof AuthenticatedSistemPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/pengaturan': {
      id: '/_authenticated/sistem/pengaturan'
      path: '/sistem/pengaturan'
      fullPath: '/sistem/pengaturan'
      preLoaderRoute: typeof AuthenticatedSistemPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistem/audit': {
      id: '/_authenticated/sistem/audit'
      path: '/sistem/audit'
      fullPath: '/sistem/audit'
      preLoaderRoute: typeof AuthenticatedSistemAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSistemAuditRoute: typeof AuthenticatedSistemAuditRoute
  AuthenticatedSistemPengaturanRoute: typeof AuthenticatedSistemPengaturanRoute
  AuthenticatedSistemPenggunaRoute: typeof AuthenticatedSistemPenggunaRoute
  AuthenticatedSistemSekolahRoute: typeof AuthenticatedSistemSekolahRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSistemAuditRoute: AuthenticatedSistemAuditRoute,
  AuthenticatedSistemPengaturanRoute: AuthenticatedSistemPengaturanRoute,
  AuthenticatedSistemPenggunaRoute: AuthenticatedSistemPenggunaRoute,
  AuthenticatedSistemSekolahRoute: AuthenticatedSistemSekolahRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
